### PR TITLE
Style the Patients index page, include pics

### PR DESCRIPTION
**Pull request by eribandogros**
What do we think of this css styling for the patients page (an index of all the patients)?
screen shot 2016-04-12 at 1 55 31 am

### CODE REVIEW

**Comment by rgulle4** [comment]
:+1: awesome

**Comment by rgulle4** [comment]
Also, I think it'd be good to go ahead and push to heroku (probably the easiest way for everyone to see what's going on). 

NB I changed the URL to <https://kennelapp.herokuapp.com/>.

To push to heroku, make sure you have the remote set up:

```
git remote -v
```

You should see `heroku  https://git.heroku.com/kennelapp.git (push)` in the output. If not, you need to add it:

```
heroku git:remote -a kennelapp
```

Now you can push to heroku. This command always pushes your local `[master]`, regardless of what branch you're currently in:

```
git push heroku
```

**Comment by rgulle4** [comment]
ETA: you need to log in to heroku before you do any of the steps above:

    heroku login

**Comment by rodomvp** [comment]
I've added the styling to the current deployment

**Pull request closed without merging**
